### PR TITLE
Add support for custom properties and date format

### PR DESCRIPTION
**Pull request by nicolnt**
This code adds the possibility to set created_on and updated_on dates based on notes frontmatter properties.

It is intended to get rid of the unstable use of filesystem dates, which notably happens when using Obsidian on different machines

I also added support for custom date and time format

image

### CODE REVIEW

**Comment by PaulTreanor** [comment]
Hi @nicolnt,
Firstly thanks for submitting your PR, this has been a requested feature since the plugin was made. I think using a combination of frontmatter and the filesystem to record creation and modification dates is an improvement over the current implementation. 

There are some issues with your pull request that would need to be fixed before I can merge it:

**1. Incorrect status bar dates**
When running your PR in a test vault the `Created on` and `Updated on` values in the status bar just showed today's date for all notes. Could you take another look at this feature, maybe with a totally new vault without other plugins installed, to see if you also get this problem?

> wrong-dates


**2. Undefined frontmatter not being found by `isValid()`**
Using `moment(updatedDateFrontmatter).isValid()` as you do in `main.ts` lines 102 and 103 doesn't ensure the date is valid. If a file has no frontmatter, `undefined` will be returned, which `isValid()` returns `true`. 

Here is this code outputting `true` in npm.runkit.com:

> moment-is-valid


Using a condition like this would cover this case:

``` js
const isValidDate = (dateFrontmatter) = { 
	return moment(dateFrontmatter).isValid() && dateFrontmatter !== undefined;
}
```


**3. Frontmatter properties never being set**
I notice that the values for the `createdDateFrontmatterProperty` and `updatedDateFrontmatterProperty` properties never get set with this code. Is an additional plugin required for this functionality? This capability is central to the feature, so it should be easy to use and work for all users. 

I think it would be cool to have this feature working for everyone. I'm totally up for helping out if you need me.

Looking forward to hearing back, 
Paul

**Comment by nicolnt** [comment]
Hi Paul,
Thanks for your review and supporting messages!

**1. Incorrect status bar dates**
Linked with **2.** as `moment(undefined)` returns the current date.

**2. Undefined frontmatter not being found by isValid()**
Instead, my update lacked some control on frontmatter date being defined. I added your snippet of code.

**3. Frontmatter properties never being set**
`createdDateFrontmatterProperty` and `updatedDateFrontmatterProperty` are set when the user enters something in the two fields in plugin settings (see screenshot below). Otherwise, they were kept as undefined.
image


I just updated the code to set it as an empty string (which would be the value if the user set the property at some point, then reverted the change). So it's more consistent. This doesn't affect previous behaviour, from what I can experience.

I did some tests by modifying created and modifed date on files from Windows [using PowerShell commands](https://www.guidingtech.com/change-date-created-and-date-modified-on-windows/) and it works.

**Comment by PaulTreanor** [comment]
Hi @nicolnt I pulled your PR and added some changes:

- I created an event listener that updates the properties of the notes when the file has been updated. This is the key change that made this feature work as expected for me. I did some testing and it seems OK but I guess we'll just have to see what users think. 
- I changed the settings so that the properties are just a toggle on and off. The properties are just called "Created_on" and "Updated_on". This is a comprimise because I think letting the users pick their own property names just makes the plugin more complicated and confusing for users. 
- I updated the README to show this new features
- I updated the README to credit you as an author

I merged the PR changes into the master branch. Thanks so much for spearheading this feature, I'm interested in hearing if you have any thoughts about it. 

Thanks, 
Paul

**Comment by nicolnt** [comment]
Hi @PaulTreanor ,
Thanks for taking some time to add some improvements.

The fact that the user cannot change the property name is a change that would make the feature useless in my use case.

Indeed, this feature where you can enter custom created modified date property names was inspired from other Obsidian community plugins I use which are [Chronology](https://obsidian.md/plugins?id=chronology) and [Contribution Graph](https://obsidian.md/plugins?id=contribution-graph). I keep created and modified dates up-to-date thanks to two other plugins, which are [Linter](https://obsidian.md/plugins?id=obsidian-linter) and [Update frontmatter modified date](https://obsidian.md/plugins?id=frontmatter-modified-date). 

All four plugins let you define the frontmatter date property name to use to either set/update or get information from.
Because of this ecosystem I already rely on a different combination of frontmatter date property name in my vault than proposed here with `created_on` and `updated_on` therefore making this **notes-dater** feature not usable in my vault.

**Comment by PaulTreanor** [comment]
This feels like such a specific workflow and feature that it's beyond the scope of the plugin and it would have a negative effect on the usability of the plugin. I think it's better to keep this as a separate fork.

**Comment by nicolnt** [comment]
Hi @PaulTreanor 

In my opinion, this makes no sense to lock the property name.

Obsidian doesn't maintain by itself such properties as `created_on` and `updated_on`. Those are necessarily user or plugin managed, and the name would also be custom.

When you say that it's a specific workflow, yes it is, and it's why I wanted to adapt the plugin to support this kind of workflow where dates are managed by plugins and templates.

Furthermore, some non-English-speaking individuals might be using property names in their language.

**Comment by nicolnt** [comment]
Hi @PaulTreanor 

Should I open a new issue to talk about this new feature? I would like to defend the possibility of being able to choose which property to use for dates.

**Comment by PaulTreanor** [comment]
Sorry for not responding very quickly @nicolnt. 

The way I implemented the properties dates seemed to not work well with other plugins either, particularly templater (according to other users). This makes me really wary of making any more changes. 

I made a new branch called `property-dates` which has the most recent updates. I set the `master` branch to be back to v1.0.1 and also labeled v1.0.2 as `prerelease` so users don't see that version. 

I really think this is better off as a fork that includes dates in the properties section of notes and to allow users to choose the names of those properties. I think this project works as intended right now and any additional features just add complexity and don't fit the simple plugin goal I had. Please feel free to fork the project and I would really happy to add a link to that fork in the README here.

**Comment by nicolnt** [comment]
No worries, I just wanted to make sure that we could discuss this. I can understand and will think whether I maintain this feature in a fork or in a branch here.

Have a nice day!

**Pull request merged**
